//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS_WS.DAL_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DAL_WS.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BUS_WS.DAL_WS.HelloWorldResponse HelloWorld(BUS_WS.DAL_WS.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetMembersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMembers", ReplyAction="*")]
        BUS_WS.DAL_WS.GetMembersResponse GetMembers(BUS_WS.DAL_WS.GetMembersRequest request);
        
        // CODEGEN: Generating message contract since element name usr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        BUS_WS.DAL_WS.LoginResponse Login(BUS_WS.DAL_WS.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        BUS_WS.DAL_WS.LogoutResponse Logout(BUS_WS.DAL_WS.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        BUS_WS.DAL_WS.RegisterResponse Register(BUS_WS.DAL_WS.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name usr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMember", ReplyAction="*")]
        BUS_WS.DAL_WS.DeleteMemberResponse DeleteMember(BUS_WS.DAL_WS.DeleteMemberRequest request);
        
        // CODEGEN: Generating message contract since element name dto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFilm", ReplyAction="*")]
        BUS_WS.DAL_WS.InsertFilmResponse InsertFilm(BUS_WS.DAL_WS.InsertFilmRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RateFilm", ReplyAction="*")]
        BUS_WS.DAL_WS.RateFilmResponse RateFilm(BUS_WS.DAL_WS.RateFilmRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFilmByName", ReplyAction="*")]
        BUS_WS.DAL_WS.SearchFilmByNameResponse SearchFilmByName(BUS_WS.DAL_WS.SearchFilmByNameRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFilm", ReplyAction="*")]
        BUS_WS.DAL_WS.UpdateFilmResponse UpdateFilm(BUS_WS.DAL_WS.UpdateFilmRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCreator", ReplyAction="*")]
        BUS_WS.DAL_WS.InsertCreatorResponse InsertCreator(BUS_WS.DAL_WS.InsertCreatorRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCreator", ReplyAction="*")]
        BUS_WS.DAL_WS.UpdateCreatorResponse UpdateCreator(BUS_WS.DAL_WS.UpdateCreatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BUS_WS.DAL_WS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BUS_WS.DAL_WS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMembers", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.GetMembersRequestBody Body;
        
        public GetMembersRequest() {
        }
        
        public GetMembersRequest(BUS_WS.DAL_WS.GetMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMembersRequestBody {
        
        public GetMembersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMembersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.GetMembersResponseBody Body;
        
        public GetMembersResponse() {
        }
        
        public GetMembersResponse(BUS_WS.DAL_WS.GetMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BUS_WS.DAL_WS.ArrayOfString GetMembersResult;
        
        public GetMembersResponseBody() {
        }
        
        public GetMembersResponseBody(BUS_WS.DAL_WS.ArrayOfString GetMembersResult) {
            this.GetMembersResult = GetMembersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(BUS_WS.DAL_WS.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usr, string pass) {
            this.usr = usr;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(BUS_WS.DAL_WS.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BUS.DAL_WS.MemberDTO LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(BUS.DAL_WS.MemberDTO LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(BUS_WS.DAL_WS.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(BUS_WS.DAL_WS.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutResponseBody {
        
        public LogoutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(BUS_WS.DAL_WS.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string xmlDetails;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string typeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pass;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string name, string phone, string email, string xmlDetails, string typeID, string usr, string pass) {
            this.name = name;
            this.phone = phone;
            this.email = email;
            this.xmlDetails = xmlDetails;
            this.typeID = typeID;
            this.usr = usr;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(BUS_WS.DAL_WS.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterResponseBody {
        
        public RegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMember", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.DeleteMemberRequestBody Body;
        
        public DeleteMemberRequest() {
        }
        
        public DeleteMemberRequest(BUS_WS.DAL_WS.DeleteMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usr;
        
        public DeleteMemberRequestBody() {
        }
        
        public DeleteMemberRequestBody(string usr) {
            this.usr = usr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.DeleteMemberResponseBody Body;
        
        public DeleteMemberResponse() {
        }
        
        public DeleteMemberResponse(BUS_WS.DAL_WS.DeleteMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteMemberResponseBody {
        
        public DeleteMemberResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFilmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFilm", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.InsertFilmRequestBody Body;
        
        public InsertFilmRequest() {
        }
        
        public InsertFilmRequest(BUS_WS.DAL_WS.InsertFilmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertFilmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BUS.DAL_WS.FilmDTO dto;
        
        public InsertFilmRequestBody() {
        }
        
        public InsertFilmRequestBody(BUS.DAL_WS.FilmDTO dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFilmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFilmResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.InsertFilmResponseBody Body;
        
        public InsertFilmResponse() {
        }
        
        public InsertFilmResponse(BUS_WS.DAL_WS.InsertFilmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertFilmResponseBody {
        
        public InsertFilmResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RateFilmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RateFilm", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.RateFilmRequestBody Body;
        
        public RateFilmRequest() {
        }
        
        public RateFilmRequest(BUS_WS.DAL_WS.RateFilmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RateFilmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int rate;
        
        public RateFilmRequestBody() {
        }
        
        public RateFilmRequestBody(string name, int rate) {
            this.name = name;
            this.rate = rate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RateFilmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RateFilmResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.RateFilmResponseBody Body;
        
        public RateFilmResponse() {
        }
        
        public RateFilmResponse(BUS_WS.DAL_WS.RateFilmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RateFilmResponseBody {
        
        public RateFilmResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchFilmByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchFilmByName", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.SearchFilmByNameRequestBody Body;
        
        public SearchFilmByNameRequest() {
        }
        
        public SearchFilmByNameRequest(BUS_WS.DAL_WS.SearchFilmByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchFilmByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public SearchFilmByNameRequestBody() {
        }
        
        public SearchFilmByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchFilmByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchFilmByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.SearchFilmByNameResponseBody Body;
        
        public SearchFilmByNameResponse() {
        }
        
        public SearchFilmByNameResponse(BUS_WS.DAL_WS.SearchFilmByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchFilmByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BUS.DAL_WS.FilmDTO[] SearchFilmByNameResult;
        
        public SearchFilmByNameResponseBody() {
        }
        
        public SearchFilmByNameResponseBody(BUS.DAL_WS.FilmDTO[] SearchFilmByNameResult) {
            this.SearchFilmByNameResult = SearchFilmByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFilmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFilm", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.UpdateFilmRequestBody Body;
        
        public UpdateFilmRequest() {
        }
        
        public UpdateFilmRequest(BUS_WS.DAL_WS.UpdateFilmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFilmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public BUS.DAL_WS.FilmDTO dto;
        
        public UpdateFilmRequestBody() {
        }
        
        public UpdateFilmRequestBody(string id, BUS.DAL_WS.FilmDTO dto) {
            this.id = id;
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFilmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFilmResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.UpdateFilmResponseBody Body;
        
        public UpdateFilmResponse() {
        }
        
        public UpdateFilmResponse(BUS_WS.DAL_WS.UpdateFilmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateFilmResponseBody {
        
        public UpdateFilmResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCreatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCreator", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.InsertCreatorRequestBody Body;
        
        public InsertCreatorRequest() {
        }
        
        public InsertCreatorRequest(BUS_WS.DAL_WS.InsertCreatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertCreatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string birth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string travia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string details;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string typeNames;
        
        public InsertCreatorRequestBody() {
        }
        
        public InsertCreatorRequestBody(string name, string birth, string travia, string details, string typeNames) {
            this.name = name;
            this.birth = birth;
            this.travia = travia;
            this.details = details;
            this.typeNames = typeNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCreatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCreatorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.InsertCreatorResponseBody Body;
        
        public InsertCreatorResponse() {
        }
        
        public InsertCreatorResponse(BUS_WS.DAL_WS.InsertCreatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertCreatorResponseBody {
        
        public InsertCreatorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCreatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCreator", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.UpdateCreatorRequestBody Body;
        
        public UpdateCreatorRequest() {
        }
        
        public UpdateCreatorRequest(BUS_WS.DAL_WS.UpdateCreatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCreatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string birth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string travia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string details;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string typeNames;
        
        public UpdateCreatorRequestBody() {
        }
        
        public UpdateCreatorRequestBody(string ID, string name, string birth, string travia, string details, string typeNames) {
            this.ID = ID;
            this.name = name;
            this.birth = birth;
            this.travia = travia;
            this.details = details;
            this.typeNames = typeNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCreatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCreatorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BUS_WS.DAL_WS.UpdateCreatorResponseBody Body;
        
        public UpdateCreatorResponse() {
        }
        
        public UpdateCreatorResponse(BUS_WS.DAL_WS.UpdateCreatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCreatorResponseBody {
        
        public UpdateCreatorResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : BUS_WS.DAL_WS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<BUS_WS.DAL_WS.Service1Soap>, BUS_WS.DAL_WS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.HelloWorldResponse BUS_WS.DAL_WS.Service1Soap.HelloWorld(BUS_WS.DAL_WS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BUS_WS.DAL_WS.HelloWorldRequest inValue = new BUS_WS.DAL_WS.HelloWorldRequest();
            inValue.Body = new BUS_WS.DAL_WS.HelloWorldRequestBody();
            BUS_WS.DAL_WS.HelloWorldResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.GetMembersResponse BUS_WS.DAL_WS.Service1Soap.GetMembers(BUS_WS.DAL_WS.GetMembersRequest request) {
            return base.Channel.GetMembers(request);
        }
        
        public BUS_WS.DAL_WS.ArrayOfString GetMembers() {
            BUS_WS.DAL_WS.GetMembersRequest inValue = new BUS_WS.DAL_WS.GetMembersRequest();
            inValue.Body = new BUS_WS.DAL_WS.GetMembersRequestBody();
            BUS_WS.DAL_WS.GetMembersResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).GetMembers(inValue);
            return retVal.Body.GetMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.LoginResponse BUS_WS.DAL_WS.Service1Soap.Login(BUS_WS.DAL_WS.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public BUS.DAL_WS.MemberDTO Login(string usr, string pass) {
            BUS_WS.DAL_WS.LoginRequest inValue = new BUS_WS.DAL_WS.LoginRequest();
            inValue.Body = new BUS_WS.DAL_WS.LoginRequestBody();
            inValue.Body.usr = usr;
            inValue.Body.pass = pass;
            BUS_WS.DAL_WS.LoginResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.LogoutResponse BUS_WS.DAL_WS.Service1Soap.Logout(BUS_WS.DAL_WS.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout(string name) {
            BUS_WS.DAL_WS.LogoutRequest inValue = new BUS_WS.DAL_WS.LogoutRequest();
            inValue.Body = new BUS_WS.DAL_WS.LogoutRequestBody();
            inValue.Body.name = name;
            BUS_WS.DAL_WS.LogoutResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.RegisterResponse BUS_WS.DAL_WS.Service1Soap.Register(BUS_WS.DAL_WS.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public void Register(string name, string phone, string email, string xmlDetails, string typeID, string usr, string pass) {
            BUS_WS.DAL_WS.RegisterRequest inValue = new BUS_WS.DAL_WS.RegisterRequest();
            inValue.Body = new BUS_WS.DAL_WS.RegisterRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            inValue.Body.email = email;
            inValue.Body.xmlDetails = xmlDetails;
            inValue.Body.typeID = typeID;
            inValue.Body.usr = usr;
            inValue.Body.pass = pass;
            BUS_WS.DAL_WS.RegisterResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).Register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.DeleteMemberResponse BUS_WS.DAL_WS.Service1Soap.DeleteMember(BUS_WS.DAL_WS.DeleteMemberRequest request) {
            return base.Channel.DeleteMember(request);
        }
        
        public void DeleteMember(string usr) {
            BUS_WS.DAL_WS.DeleteMemberRequest inValue = new BUS_WS.DAL_WS.DeleteMemberRequest();
            inValue.Body = new BUS_WS.DAL_WS.DeleteMemberRequestBody();
            inValue.Body.usr = usr;
            BUS_WS.DAL_WS.DeleteMemberResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).DeleteMember(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.InsertFilmResponse BUS_WS.DAL_WS.Service1Soap.InsertFilm(BUS_WS.DAL_WS.InsertFilmRequest request) {
            return base.Channel.InsertFilm(request);
        }
        
        public void InsertFilm(BUS.DAL_WS.FilmDTO dto) {
            BUS_WS.DAL_WS.InsertFilmRequest inValue = new BUS_WS.DAL_WS.InsertFilmRequest();
            inValue.Body = new BUS_WS.DAL_WS.InsertFilmRequestBody();
            inValue.Body.dto = dto;
            BUS_WS.DAL_WS.InsertFilmResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).InsertFilm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.RateFilmResponse BUS_WS.DAL_WS.Service1Soap.RateFilm(BUS_WS.DAL_WS.RateFilmRequest request) {
            return base.Channel.RateFilm(request);
        }
        
        public void RateFilm(string name, int rate) {
            BUS_WS.DAL_WS.RateFilmRequest inValue = new BUS_WS.DAL_WS.RateFilmRequest();
            inValue.Body = new BUS_WS.DAL_WS.RateFilmRequestBody();
            inValue.Body.name = name;
            inValue.Body.rate = rate;
            BUS_WS.DAL_WS.RateFilmResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).RateFilm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.SearchFilmByNameResponse BUS_WS.DAL_WS.Service1Soap.SearchFilmByName(BUS_WS.DAL_WS.SearchFilmByNameRequest request) {
            return base.Channel.SearchFilmByName(request);
        }
        
        public BUS.DAL_WS.FilmDTO[] SearchFilmByName(string name) {
            BUS_WS.DAL_WS.SearchFilmByNameRequest inValue = new BUS_WS.DAL_WS.SearchFilmByNameRequest();
            inValue.Body = new BUS_WS.DAL_WS.SearchFilmByNameRequestBody();
            inValue.Body.name = name;
            BUS_WS.DAL_WS.SearchFilmByNameResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).SearchFilmByName(inValue);
            return retVal.Body.SearchFilmByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.UpdateFilmResponse BUS_WS.DAL_WS.Service1Soap.UpdateFilm(BUS_WS.DAL_WS.UpdateFilmRequest request) {
            return base.Channel.UpdateFilm(request);
        }
        
        public void UpdateFilm(string id, BUS.DAL_WS.FilmDTO dto) {
            BUS_WS.DAL_WS.UpdateFilmRequest inValue = new BUS_WS.DAL_WS.UpdateFilmRequest();
            inValue.Body = new BUS_WS.DAL_WS.UpdateFilmRequestBody();
            inValue.Body.id = id;
            inValue.Body.dto = dto;
            BUS_WS.DAL_WS.UpdateFilmResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).UpdateFilm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.InsertCreatorResponse BUS_WS.DAL_WS.Service1Soap.InsertCreator(BUS_WS.DAL_WS.InsertCreatorRequest request) {
            return base.Channel.InsertCreator(request);
        }
        
        public void InsertCreator(string name, string birth, string travia, string details, string typeNames) {
            BUS_WS.DAL_WS.InsertCreatorRequest inValue = new BUS_WS.DAL_WS.InsertCreatorRequest();
            inValue.Body = new BUS_WS.DAL_WS.InsertCreatorRequestBody();
            inValue.Body.name = name;
            inValue.Body.birth = birth;
            inValue.Body.travia = travia;
            inValue.Body.details = details;
            inValue.Body.typeNames = typeNames;
            BUS_WS.DAL_WS.InsertCreatorResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).InsertCreator(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BUS_WS.DAL_WS.UpdateCreatorResponse BUS_WS.DAL_WS.Service1Soap.UpdateCreator(BUS_WS.DAL_WS.UpdateCreatorRequest request) {
            return base.Channel.UpdateCreator(request);
        }
        
        public void UpdateCreator(string ID, string name, string birth, string travia, string details, string typeNames) {
            BUS_WS.DAL_WS.UpdateCreatorRequest inValue = new BUS_WS.DAL_WS.UpdateCreatorRequest();
            inValue.Body = new BUS_WS.DAL_WS.UpdateCreatorRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.birth = birth;
            inValue.Body.travia = travia;
            inValue.Body.details = details;
            inValue.Body.typeNames = typeNames;
            BUS_WS.DAL_WS.UpdateCreatorResponse retVal = ((BUS_WS.DAL_WS.Service1Soap)(this)).UpdateCreator(inValue);
        }
    }
}
