//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using QLHS_WCF;

namespace Host.ServiceReference2 {
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName = "ServiceReference2.IService1")]
    public interface IService1 {
        [OperationContract(Action = "http://tempuri.org/IService1/GetData",
            ReplyAction = "http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);

        [OperationContract(Action = "http://tempuri.org/IService1/GetAllStudents",
            ReplyAction = "http://tempuri.org/IService1/GetAllStudentsResponse")]
        StudentDTO[] GetAllStudents();

        [OperationContract(Action = "http://tempuri.org/IService1/DeleteStudent",
            ReplyAction = "http://tempuri.org/IService1/DeleteStudentResponse")]
        bool DeleteStudent(StudentDTO student);

        [OperationContract(Action = "http://tempuri.org/IService1/UpdateStudent",
            ReplyAction = "http://tempuri.org/IService1/UpdateStudentResponse")]
        bool UpdateStudent(StudentDTO student);

        [OperationContract(Action = "http://tempuri.org/IService1/CreateStudent",
            ReplyAction = "http://tempuri.org/IService1/CreateStudentResponse")]
        void CreateStudent(StudentDTO student);
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : IService1, IClientChannel {
    }

    [DebuggerStepThrough]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public class Service1Client : ClientBase<IService1>, IService1 {
        public Service1Client() {
        }

        public Service1Client(string endpointConfigurationName) :
            base(endpointConfigurationName) {
        }

        public Service1Client(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress) {
        }

        public Service1Client(string endpointConfigurationName, EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress) {
        }

        public Service1Client(Binding binding, EndpointAddress remoteAddress) :
            base(binding, remoteAddress) {
        }

        #region IService1 Members

        public string GetData(int value) {
            return base.Channel.GetData(value);
        }

        public StudentDTO[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }

        public bool DeleteStudent(StudentDTO student) {
            return base.Channel.DeleteStudent(student);
        }

        public bool UpdateStudent(StudentDTO student) {
            return base.Channel.UpdateStudent(student);
        }

        public void CreateStudent(StudentDTO student) {
            base.Channel.CreateStudent(student);
        }

        #endregion
    }
}